
.PHONY: all

all:
	$(MAKE) -C minlzlib 
	$(MAKE) -C dlmalloc 
	$(MAKE) -C gdbstub 
	$(MAKE) -C doom 

clean:
	$(MAKE) -C minlzlib clean
	$(MAKE) -C dlmalloc clean
	$(MAKE) -C gdbstub clean
	$(MAKE) -C doom clean

cleanall:
	$(MAKE) -C minlzlib cleanall
	$(MAKE) -C dlmalloc cleanall
	$(MAKE) -C gdbstub cleanall
	$(MAKE) -C doom cleanall
